name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Configure Poetry to not create virtualenvs
        run: poetry config virtualenvs.create false

      - name: Install dependencies
        run: make install

      - name: Run linter
        run: make lint

      - name: Run tests with coverage
        run: make test-coverage
      
      - name: Debug print token length
        run: echo "${{ secrets.CC_TEST_REPORTER_ID }}" | wc -c

      - name: Upload coverage to CodeClimate
        uses: paambaati/codeclimate-action@v3.0.0
        with:
          coverageCommand: 'make test-coverage'
          coverageLocations: 'coverage.xml'  # <-- debe ser string no vacío
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Run CLI diff command test
        run: make run-diff
